#!/bin/sh
#
# /etc/rc.d/fcron: start/stop fcron daemon
#

case $1 in
start)
	/usr/sbin/fcron -b
	if [ ! -f /var/spool/fcron/systab ]; then
	   /usr/bin/fcrontab -u systab -z
	fi
	;;
stop)
	killall -q /usr/sbin/fcron
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
