#!/bin/sh
#
# /etc/rc.d/dnsmasq: start/stop dnsmasq daemon
#

case $1 in
start)
	/usr/sbin/dnsmasq
	;;
stop)
	killall -q /usr/sbin/dnsmasq
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
reload)
	kill -s HUP $(pidof dnsmasq)
	;;
*)
	echo "usage: $0 [start|stop|restart|reload]"
	;;
esac

# End of file
