#!/bin/sh
#
# /etc/rc.d/vsftpd: start/stop vsftpd daemon
#

CRT=/etc/ssl/certs/vsftpd.pem

make_cert() {
	FQDN=$(hostname -f) || FQDN=localhost
	echo "Creating SSL certificate $CRT for host $FQDN"
	INFO=".\n.\n.\n.\n.\n$FQDN\nroot@$FQDN"
	OPTS="req -new -nodes -x509 -days 365 -newkey rsa:1024" 
	echo -e $INFO | openssl $OPTS -out $CRT -keyout $CRT 2> /dev/null
	chmod 0600 $CRT
}


case $1 in
start)
	if [ ! -s $CRT ]; then 
		make_cert
	fi
	setsid /usr/sbin/vsftpd &
	;;
stop)
	killall -q /usr/sbin/vsftpd
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
