#!/bin/sh
#
# /etc/rc.d/ntpd: start/stop ntpd daemon
#

case $1 in
    start)
	/usr/sbin/ntpd -s
	;;
    stop)
	killall -q /usr/sbin/ntpd
	;;
    restart)
	$0 stop
	sleep 2
	$0 start
	;;
    *)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
