#!/bin/sh
#
# /etc/rc.d/maradns: start/stop mara DNS server
#

case $1 in
start)
	setsid /usr/sbin/maradns >> /var/log/maradns.log &
	;;
stop)
	killall -q /usr/sbin/maradns
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
