#!/bin/sh

# check for messagebus group or add one
getent group messagebus || /usr/sbin/groupadd -g 81 messagebus

# check for messagebus user or add one
getent passwd messagebus || /usr/sbin/useradd -g messagebus -u 81 -d /var/empty -s /bin/false -c "D-BUS System Messagebus User" messagebus

# lock the account
/usr/bin/passwd -l messagebus
