#!/bin/sh
#
# /etc/rc.d/xdm: start/stop X display manager
#

case $1 in
start)
	. /etc/profile
	/usr/X11R6/bin/xdm
	;;
stop)
	killall -q /usr/X11R6/bin/xdm
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
