#!/bin/sh
#
# /etc/rc.d/httpd: start/stop webfs http daemon
#

case $1 in
start)
	/usr/bin/webfsd -u www -g www -r /var/www -p 80 -f index.html
	;;
stop)
	killall -q /usr/bin/webfsd
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
