#!/bin/sh
#
# /etc/rc.d/smartd: start/stop smartd daemon
#

case $1 in
start)
	/usr/sbin/smartd -p /var/run/smartd.pid
	;;
stop)
	killall -q /usr/sbin/smartd
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
reload)
	kill -HUP `pidof smartd`
	;;
*)
	echo "usage: $0 [start|stop|restart|reload]"
	;;
esac

# End of file
