#!/bin/sh

/usr/bin/grep -q ^bitlbee: /etc/group
if [ $? -eq 1 ] ; then
	/usr/sbin/groupadd bitlbee
fi

/usr/bin/grep -q ^bitlbee: /etc/passwd
if [ $? -eq 1 ] ; then
	/usr/sbin/useradd -g bitlbee -c BitlBee -d /var/lib/bitlbee -s /bin/false bitlbee
	/usr/bin/passwd -l bitlbee
fi
