#!/bin/sh
#
# /etc/rc.d/tomcat: start/stop jakarta tomcat servlet container
#

case "$1" in
    start)
        /usr/lib/tomcat/bin/startup.sh
        ;;
    stop)
        /usr/lib/tomcat/bin/shutdown.sh
        ;;
    restart)
        /usr/lib/tomcat/bin/shutdown.sh
        /usr/lib/tomcat/bin/startup.sh
        ;;
    *)
        echo "usage: $0 start|stop|restart"
        ;;
esac

# End of file
