#!/bin/bash
#
# /etc/rc.d/oidentd
#

case "$1" in
start)
	/usr/sbin/oidentd -C /etc/oidentd.conf -u nobody -l 10 
	;;
stop)
	killall /usr/sbin/oidentd
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop}"
	;;
esac

#
# End of file
#
