#!/bin/sh
#
# /etc/rc.d/masqmail: start/stop masqmail SMTP daemon
#

case $1 in
start)
	/usr/sbin/masqmail -bd -q20m 
	;;
stop)
	killall -q /usr/sbin/masqmail
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
