#!/bin/sh

version=1.70.1
MASTER_CAT=/etc/xml/catalog
XSL_PATH=file:///usr/share/xml/xsl/docbook/$version
XSL_URLS="http://docbook.sourceforge.net/release/xsl/$version
          http://docbook.sourceforge.net/release/xsl/current"

for url in $XSL_URLS; do
	xmlcatalog --noout --add "rewriteURI" \
	  "$url" "$XSL_PATH" $MASTER_CAT
done

# End of file
